### ISSUE TITLE
Figure out how to get commit credits from Drupal 7 Shortcut

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/shortcut#1]
See https://github.com/drupal/drupal/tree/7.x/modules/shortcut

**Comment by docwilmot** [comment]
I did this for Forum and Statistics: https://nering.dev/2016/git-convert-a-folder-to-another-repository-or-a-git-submodule/

**Comment by alanmels** [comment]
@docwilmot, thanks a lot for the right link. Let me post the exact steps I took for future references:

```
git clone https://github.com/drupal/drupal.git --branch 7.x
cd drupal/
git remote -v
git remote remove origin
git filter-branch --subdirectory-filter modules/shortcut -- --all
```

I had to wait for some time for the process to finish. After that I deleted of the files in the directory, but the `.git` directory, copied all the ported files and performed:

```
git branch -m main master
git add .
git commit -m "Initial port to Backdrop"
git remote set-url origin https://github.com/backdrop-contrib/shortcut.git
git push origin master --force
```
