### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/shortcut#2]
I just wanted to let you know that I installed this module and did a pretty simple test without any issues. I did the following:

* Enabled the module
* Added a couple of shortcut links
* Added a block on the front page to display those links

Seems to work pretty well so far.

**Comment by alanmels** [comment]
@stpaultim Tim, thanks for your feedback. Instead of using blocks, I really wanted to restore original Drupal 7 like behavior, but due to other things popped up had to put this project for later.

**Comment by stpaultim** [comment]
@alanmels - That makes sense. I don't have clear memory of the Drupal 7 behavior, but vaguely recall shortcuts being in the admin menu. I never used them.

I was checking your port of this module in the context of this discussion in core issue queue (to see if might help): https://github.com/backdrop/backdrop-issues/issues/4692

I understand that this module is not yet complete. Thanks for working on it.

**Comment by alanmels** [comment]
This has been fixed and now the shortcuts can be accessed on the admin bar.
